import React, { useState, useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [state, setState] = useState({
    posts: [],
  })

  useEffect(() => {
      fetch('https://www.thecocktaildb.com/api/json/v1/1/search.php?f=a')
              .then(response => response.json())
              .then(result => {
                  setState({ posts: result.drinks })
      })
  })

  return (
    <div className='bg-main-pattern bg-cover h-screen p-5  grid grid-rows-3'>
      <Head>
        <title>The Cocktail</title>
        <meta name="description" content="Generated by YudhaImam" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='grid justify-center items-center h-full row-span-3'>
        <div className="text-center">
        <h1 className='text-white text-5xl text-center'>
          Welcome to <Link href="/drink">The Cocktail</Link>
        </h1>
        <Link href="/drink">
          <button className="bg-white py-3 px-5 mt-5 rounded-lg font-semiblod hover:outline-dashed hover:outline-white hover:text-white hover:bg-transparent transition ease-in-out duration-200">
          See Drink List
          </button>
        </Link>
        </div>

          {/* { state.posts.length > 0 && state.posts.map(i => <Slide key={i.idDrink} drink={i} />)} */}
      </main>
      <footer className=' grid items-end justify-center '>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer" className="text-white flex" 
        >
          Powered by <p className="ml-1 hover:animate-bounce">
          YudhaImam </p> 
        </a>
      </footer>

    </div>
  )
}
